# Generated by Django 4.2 on 2026-04-21 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_booking_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_datetime', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('max_participants', models.PositiveIntegerField(default=10, verbose_name='Максимум участников')),
                ('current_participants', models.PositiveIntegerField(default=0, verbose_name='Текущее количество записавшихся')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('cancelled', 'Отменён'), ('completed', 'Завершён')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('masterclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='main.masterclass', verbose_name='Мастер-класс')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.session', verbose_name='Сеанс'),
        ),
    ]
