# Generated by Django 4.2 on 2026-04-21 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_session_booking_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterclass',
            options={'ordering': ['-created_at'], 'verbose_name': 'Мастер-класс', 'verbose_name_plural': 'Мастер-классы'},
        ),
        migrations.RemoveIndex(
            model_name='masterclass',
            name='main_master_start_d_89b628_idx',
        ),
        migrations.RemoveField(
            model_name='masterclass',
            name='current_participants',
        ),
        migrations.RemoveField(
            model_name='masterclass',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='masterclass',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='masterclass',
            name='start_datetime',
        ),
    ]
