# Generated by Django 4.2 on 2026-05-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_masterclass_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на онлайн-трансляцию (Zoom, Яндекс.Телемост и т.д.)'),
        ),
    ]
