# Generated by Django 4.2 on 2026-05-31 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.session', verbose_name='Сеанс'),
        ),
    ]
