# Generated by Django 4.2 on 2026-06-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_booking_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
