# Generated by Django 4.2 on 2026-06-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к бронированию'),
        ),
    ]
